"""Users table

Revision ID: 118dca3c10f4
Revises: 
Create Date: 2022-09-13 22:16:21.154954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '118dca3c10f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
