"""Added used_at field on confirmations table

Revision ID: 34b07fea0921
Revises: 497565841751
Create Date: 2022-09-16 23:47:55.880773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34b07fea0921'
down_revision = '497565841751'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('confirmations', sa.Column('used_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('confirmations', 'used_at')
    # ### end Alembic commands ###
