"""Added confirmations table

Revision ID: 497565841751
Revises: ebcd523f594d
Create Date: 2022-09-16 23:12:39.719553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '497565841751'
down_revision = 'ebcd523f594d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('confirmations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('secret', sa.String(), nullable=True),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_confirmations_id'), 'confirmations', ['id'], unique=False)
    op.create_index(op.f('ix_confirmations_secret'), 'confirmations', ['secret'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_confirmations_secret'), table_name='confirmations')
    op.drop_index(op.f('ix_confirmations_id'), table_name='confirmations')
    op.drop_table('confirmations')
    # ### end Alembic commands ###
